project_id = "jeurznrjcohqbevrzses"

[functions.image-proxy]
verify_jwt = false

[functions.dalle-image]
verify_jwt = false

[functions.openai-image-edit]
verify_jwt = false

[functions.openai-image-variations]
verify_jwt = false

[functions.veo2-video]
verify_jwt = false

[functions.veo3-video]
verify_jwt = false

[functions.gemini-chat]
verify_jwt = true

[functions.perplexity-chat]
verify_jwt = true